package com.rizqi.tms.utility

const val PASSWORD_PATTERN = "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[.@#$%^&+=]).{8,}$"
const val TMS_DATABASE = "tms_database"
const val MENU_INDEX = "menu_index"
const val DASHBOARD_STATE = "dashboard_state"
const val BARCODE_NUMBER = "barcode_number"
const val BYTE_ARRAY = "byte_array"
const val BITMAP_JPG = "bitmap.jpg"
const val CONNECTOR_TEXT_FORMAT = "%s = 1 %s"
const val ANDROID_DATA = "/Android/data/"
const val FILES = "/Files"
const val IMAGE_NAME_FORMAT = "IMG_%d.jpg"
const val ITEM_NO_BARCODE = "\'Barang tanpa barcode\'"
const val ITEM_ID = "item_id"
const val SEARCH_FILTER = "search_filter"
const val BACKUP_NOTIFICATION_CHANNEL_ID = "backup_notification"
const val BACKUP_NOTIFICATION_CHANNEL_NAME = "Backup"
const val BACKUP_NOTIFICATION_ID = 4243
const val TRANSACTION_ID = "transaction_id"
const val EEE_DD_MMM_YYYY = "EEEE, dd MMMM yyyy"
const val DD_MMM_YYYY = "dd MMMM yyyy"
const val EEE_DD_MMM_YYYY_HH_MM = "EEEE, dd MMMM yyyy  HH:mm"
const val BACKUP_REFERENCE = "backup"
const val ITEMS_REFERENCE = "items"
const val TRANSACTIONS_REFERENCE = "transactions"
const val UNITS_REFERENCE = "units"
const val APP_BLUETOOTH_DEVICE = "app_bluetooth_device"
const val MERCHANT_IMAGE_ID = "merchant_image"
const val MERCHANT_NAME_ID = "merchant_name"
const val MERCHANT_ADDRESS_ID = "merchant_address"
const val MERCHANT_CASHIER_ID = "merchant_cashier"
const val MERCHANT_DATE_ID = "merchant_date"
const val MERCHANT_TRANSACTION_ID_ID = "merchant_transaction_id"