package com.rizqi.tms.utility

const val PASSWORD_PATTERN = "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[.@#$%^&+=]).{8,}$"
const val TMS_DATABASE = "tms_database"
const val MENU_INDEX = "menu_index"
const val DASHBOARD_STATE = "dashboard_state"
const val BARCODE_NUMBER = "barcode_number"
const val BYTE_ARRAY = "byte_array"
const val BITMAP_JPG = "bitmap.jpg"
const val CONNECTOR_TEXT_FORMAT = "%s = 1 %s"
const val ANDROID_DATA = "/Android/data/"
const val FILES = "/Files"
const val IMAGE_NAME_FORMAT = "IMG_%d.jpg"
const val ITEM_NO_BARCODE = "\'Barang tanpa barcode\'"
const val ITEM_ID = "item_id"